allow missing values in columns partial fix for #267
previously the code would fail with:

  DimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'someunit' ([mass]).